repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(src|tests|scripts)/.+\.py$
      - id: ruff-format
        files: ^(src|tests|scripts)/.+\.py$
